class CreateTableVariable3Zip < ActiveRecord::Migration
  def up
  	create_table :variable_3zips do |t|
  		t.string :zip
		t.integer :varid_1
		t.integer :varid_2
		t.integer :varid_3
		t.integer :varid_4
		t.integer :varid_5
		t.integer :varid_6
		t.integer :varid_7
		t.integer :varid_8
		t.integer :varid_9
		t.integer :varid_10
		t.integer :varid_11
		t.integer :varid_12
		t.integer :varid_13
		t.integer :varid_14
		t.integer :varid_15
		t.integer :varid_16
		t.integer :varid_17
		t.integer :varid_18
		t.integer :varid_19
		t.integer :varid_20
		t.integer :varid_21
		t.integer :varid_22
		t.integer :varid_23
		t.integer :varid_24
		t.integer :varid_25
		t.integer :varid_26
		t.integer :varid_27
		t.integer :varid_28
		t.integer :varid_29
		t.integer :varid_30
		t.integer :varid_31
		t.integer :varid_32
		t.integer :varid_33
		t.integer :varid_34
		t.integer :varid_35
		t.integer :varid_36
		t.integer :varid_37
		t.integer :varid_38
		t.integer :varid_39
		t.integer :varid_40
		t.integer :varid_41
		t.integer :varid_42
		t.integer :varid_43
		t.integer :varid_44
		t.integer :varid_45
		t.integer :varid_46
		t.integer :varid_47
		t.integer :varid_48
		t.integer :varid_49
		t.integer :varid_50
		t.integer :varid_51
		t.integer :varid_52
		t.integer :varid_53
		t.integer :varid_54
		t.integer :varid_55
		t.integer :varid_56
		t.integer :varid_57
		t.integer :varid_58
		t.integer :varid_59
		t.integer :varid_60
		t.integer :varid_61
		t.integer :varid_62
		t.integer :varid_63
		t.integer :varid_64
		t.integer :varid_65
		t.integer :varid_66
		t.integer :varid_67
		t.integer :varid_68
		t.integer :varid_69
		t.integer :varid_70
		t.integer :varid_71
		t.integer :varid_72
		t.integer :varid_73
		t.integer :varid_74
		t.integer :varid_75
		t.integer :varid_76
		t.integer :varid_77
		t.integer :varid_78
		t.integer :varid_79
		t.integer :varid_80
		t.integer :varid_81
		t.integer :varid_82
		t.integer :varid_83
		t.integer :varid_84
		t.integer :varid_85
		t.integer :varid_86
		t.integer :varid_87
		t.integer :varid_88
		t.integer :varid_89
		t.integer :varid_90
		t.integer :varid_91
		t.integer :varid_92
		t.integer :varid_93
		t.integer :varid_94
		t.integer :varid_95
		t.integer :varid_96
		t.integer :varid_97
		t.integer :varid_98
		t.integer :varid_99
		t.integer :varid_100
		t.integer :varid_101
		t.integer :varid_102
		t.integer :varid_103
		t.integer :varid_104
		t.integer :varid_105
		t.integer :varid_106
		t.integer :varid_107
		t.integer :varid_108
		t.integer :varid_109
		t.integer :varid_110
		t.integer :varid_111
		t.integer :varid_112
		t.integer :varid_113
		t.integer :varid_114
		t.integer :varid_115
		t.integer :varid_116
		t.integer :varid_117
		t.integer :varid_118
		t.integer :varid_119
		t.integer :varid_120
		t.integer :varid_121
		t.integer :varid_122
		t.integer :varid_123
		t.integer :varid_124
		t.integer :varid_125
		t.integer :varid_126
		t.integer :varid_127
		t.integer :varid_128
		t.integer :varid_129
		t.integer :varid_130
		t.integer :varid_131
		t.integer :varid_132
		t.integer :varid_133
		t.integer :varid_134
		t.integer :varid_135
		t.integer :varid_136
		t.integer :varid_137
		t.integer :varid_138
		t.integer :varid_139
		t.integer :varid_140
		t.integer :varid_141
		t.integer :varid_142
		t.integer :varid_143
		t.integer :varid_144
		t.integer :varid_145
		t.integer :varid_146
		t.integer :varid_147
		t.integer :varid_148
		t.integer :varid_149
		t.integer :varid_150
  		

  		t.timestamps
  	end
  end

  def down
  	drop_table :variable_3zips
  end
end
