class ChangeVariable3ZipColTypes < ActiveRecord::Migration
  def change
  	change_table :variable3_zips do |t|
  	  t.change :varid_1, :numeric
  	  t.change :varid_2, :numeric
  	  t.change :varid_3, :numeric
  	  t.change :varid_4, :numeric
  	  t.change :varid_5, :numeric
  	  t.change :varid_6, :numeric
  	  t.change :varid_7, :numeric
  	  t.change :varid_8, :numeric
  	  t.change :varid_9, :numeric
  	  t.change :varid_10, :numeric
  	  t.change :varid_11, :numeric
  	  t.change :varid_12, :numeric
  	  t.change :varid_13, :numeric
  	  t.change :varid_14, :numeric
  	  t.change :varid_15, :numeric
  	  t.change :varid_16, :numeric
  	  t.change :varid_17, :numeric
  	  t.change :varid_18, :numeric
  	  t.change :varid_19, :numeric
  	  t.change :varid_20, :numeric
  	  t.change :varid_21, :numeric
  	  t.change :varid_22, :numeric
  	  t.change :varid_23, :numeric
  	  t.change :varid_24, :numeric
  	  t.change :varid_25, :numeric
  	  t.change :varid_26, :numeric
  	  t.change :varid_27, :numeric
  	  t.change :varid_28, :numeric
  	  t.change :varid_29, :numeric
  	  t.change :varid_30, :numeric
  	  t.change :varid_31, :numeric
  	  t.change :varid_32, :numeric
  	  t.change :varid_33, :numeric
  	  t.change :varid_34, :numeric
  	  t.change :varid_35, :numeric
  	  t.change :varid_36, :numeric
  	  t.change :varid_37, :numeric
  	  t.change :varid_38, :numeric
  	  t.change :varid_39, :numeric
  	  t.change :varid_40, :numeric
  	  t.change :varid_41, :numeric
  	  t.change :varid_42, :numeric
  	  t.change :varid_43, :numeric
  	  t.change :varid_44, :numeric
  	  t.change :varid_45, :numeric
  	  t.change :varid_46, :numeric
  	  t.change :varid_47, :numeric
  	  t.change :varid_48, :numeric
  	  t.change :varid_49, :numeric
  	  t.change :varid_50, :numeric
  	  t.change :varid_51, :numeric
  	  t.change :varid_52, :numeric
  	  t.change :varid_53, :numeric
  	  t.change :varid_54, :numeric
  	  t.change :varid_55, :numeric
  	  t.change :varid_56, :numeric
  	  t.change :varid_57, :numeric
  	  t.change :varid_58, :numeric
  	  t.change :varid_59, :numeric
  	  t.change :varid_60, :numeric
  	  t.change :varid_61, :numeric
  	  t.change :varid_62, :numeric
  	  t.change :varid_63, :numeric
  	  t.change :varid_64, :numeric
  	  t.change :varid_65, :numeric
  	  t.change :varid_66, :numeric
  	  t.change :varid_67, :numeric
  	  t.change :varid_68, :numeric
  	  t.change :varid_69, :numeric
  	  t.change :varid_70, :numeric
  	  t.change :varid_71, :numeric
  	  t.change :varid_72, :numeric
  	  t.change :varid_73, :numeric
  	  t.change :varid_74, :numeric
  	  t.change :varid_75, :numeric
  	  t.change :varid_76, :numeric
  	  t.change :varid_77, :numeric
  	  t.change :varid_78, :numeric
  	  t.change :varid_79, :numeric
  	  t.change :varid_80, :numeric
  	  t.change :varid_81, :numeric
  	  t.change :varid_82, :numeric
  	  t.change :varid_83, :numeric
  	  t.change :varid_84, :numeric
  	  t.change :varid_85, :numeric
  	  t.change :varid_86, :numeric
  	  t.change :varid_87, :numeric
  	  t.change :varid_88, :numeric
  	  t.change :varid_89, :numeric
  	  t.change :varid_90, :numeric
  	  t.change :varid_91, :numeric
  	  t.change :varid_92, :numeric
  	  t.change :varid_93, :numeric
  	  t.change :varid_94, :numeric
  	  t.change :varid_95, :numeric
  	  t.change :varid_96, :numeric
  	  t.change :varid_97, :numeric
  	  t.change :varid_98, :numeric
  	  t.change :varid_99, :numeric
  	  t.change :varid_100, :numeric
  	  t.change :varid_101, :numeric
  	  t.change :varid_102, :numeric
  	  t.change :varid_103, :numeric
  	  t.change :varid_104, :numeric
  	  t.change :varid_105, :numeric
  	  t.change :varid_106, :numeric
  	  t.change :varid_107, :numeric
  	  t.change :varid_108, :numeric
  	  t.change :varid_109, :numeric
  	  t.change :varid_110, :numeric
  	  t.change :varid_111, :numeric
  	  t.change :varid_112, :numeric
  	  t.change :varid_113, :numeric
  	  t.change :varid_114, :numeric
  	  t.change :varid_115, :numeric
  	  t.change :varid_116, :numeric
  	end
  end
end
